name = "Dollhouse"
author = "Lilith"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05933673a3d53febaa267ea492d96e2f8d5f0eadef1962469883a70d9240257a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
