name = "Dollhouse"
author = "Lilith"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb9c42db8a1b3b79d1846d1b198730ed577db95209d3665bf2d492c388fd7341"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
